export const FACTORY_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_feeCollector", type: "address" },
      { name: "_feeBasisPoints", type: "uint16" },
    ],
  },
  {
    type: "function",
    name: "createCampaign",
    inputs: [
      { name: "_recipient", type: "address" },
      { name: "_fundingGoal", type: "uint256" },
      { name: "_startTime", type: "uint256" },
      { name: "_endTime", type: "uint256" },
      { name: "_metadataURI", type: "string" },
    ],
    outputs: [{ type: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAllCampaigns",
    inputs: [],
    outputs: [{ type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCampaignCount",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCreatorCampaigns",
    inputs: [{ name: "creator", type: "address" }],
    outputs: [{ type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isCampaign",
    inputs: [{ type: "address" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeBasisPoints",
    inputs: [],
    outputs: [{ type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "CampaignCreated",
    inputs: [
      { name: "campaign", type: "address", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "recipient", type: "address", indexed: true },
      { name: "fundingGoal", type: "uint256", indexed: false },
      { name: "startTime", type: "uint256", indexed: false },
      { name: "endTime", type: "uint256", indexed: false },
      { name: "metadataURI", type: "string", indexed: false },
    ],
  },
] as const;

export const CAMPAIGN_ABI = [
  {
    type: "function",
    name: "getCampaignInfo",
    inputs: [],
    outputs: [
      { name: "_recipient", type: "address" },
      { name: "_fundingGoal", type: "uint256" },
      { name: "_totalRaised", type: "uint256" },
      { name: "_startTime", type: "uint256" },
      { name: "_endTime", type: "uint256" },
      { name: "_status", type: "uint8" },
      { name: "_donorCount", type: "uint256" },
      { name: "_milestoneCount", type: "uint256" },
      { name: "_metadataURI", type: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "donate",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "donateShielded",
    inputs: [{ name: "commitmentHash", type: "bytes32" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "createMilestoneMatch",
    inputs: [
      { name: "milestoneThreshold", type: "uint256" },
      { name: "matchAmount", type: "uint256" },
      { name: "isPrivate", type: "bool" },
      { name: "commitmentHash", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "finalize",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimFunds",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "refund",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "refundShielded",
    inputs: [
      { name: "commitmentHash", type: "bytes32" },
      { name: "secret", type: "bytes32" },
      { name: "nullifier", type: "bytes32" },
      { name: "refundTo", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "refundMatch",
    inputs: [{ name: "matchIndex", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "batchRefund",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "totalRaised",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fundingGoal",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "status",
    inputs: [],
    outputs: [{ type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "recipient",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "donations",
    inputs: [{ type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDonorCount",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDonors",
    inputs: [],
    outputs: [{ type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMilestoneMatches",
    inputs: [],
    outputs: [
      {
        type: "tuple[]",
        components: [
          { name: "matcher", type: "address" },
          { name: "commitmentHash", type: "bytes32" },
          { name: "milestoneThreshold", type: "uint256" },
          { name: "matchAmount", type: "uint256" },
          { name: "isPrivate", type: "bool" },
          { name: "isActivated", type: "bool" },
          { name: "isFunded", type: "bool" },
          { name: "isRefunded", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMilestoneMatchCount",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "shieldedDonationCount",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "shieldedDonationTotal",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "recipientClaimed",
    inputs: [],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "startTime",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "endTime",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeBasisPoints",
    inputs: [],
    outputs: [{ type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "metadataURI",
    inputs: [],
    outputs: [{ type: "string" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "DonationReceived",
    inputs: [
      { name: "donor", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ShieldedDonationReceived",
    inputs: [
      { name: "commitmentIndex", type: "uint256", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CampaignFinalized",
    inputs: [
      { name: "status", type: "uint8", indexed: false },
      { name: "totalRaised", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "MilestoneMatchCreated",
    inputs: [
      { name: "matchIndex", type: "uint256", indexed: true },
      { name: "threshold", type: "uint256", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "isPrivate", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "MilestoneActivated",
    inputs: [{ name: "matchIndex", type: "uint256", indexed: true }],
  },
] as const;
